blank_issues_enabled: true
contact_links:
  - name: MS Annika Discussions
    url: https://github.com/hgb-bin-proteomics/MSAnnika/discussions
    about: Please ask and answer questions here.
  - name: Contact us directly
    url: https://github.com/hgb-bin-proteomics/MSAnnika?tab=readme-ov-file#contact
    about: In case you want to reach us directly please write us at this email.
